'use strict';
const $=id=>document.getElementById(id);
const parser=window.SculpyParser, storageKey='sculpy-demo-records-v1';
let records=[],draft=null,recognition=null,listening=false,listenTimer=null,toastTimer=null,speechError=false,storageAvailable=true;
try{const loaded=JSON.parse(localStorage.getItem(storageKey)||'[]');if(!Array.isArray(loaded))throw Error();records=loaded.filter(r=>r&&typeof r.id==='string'&&typeof r.customer==='string'&&typeof r.raw==='string');}catch{storageAvailable=false;}
function status(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
function message(text,role='assistant') {const item=document.createElement('div');item.className='message '+role;const who=document.createElement('span');who.className='speaker';who.textContent=role==='assistant'?'SCULPY':'YOU';const p=document.createElement('p');p.textContent=text;item.append(who,p);$('messages').append(item);$('messages').scrollTop=$('messages').scrollHeight;}
function say(text){if(!$('speak').checked||!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(text);utterance.lang='zh-CN';utterance.rate=1;window.speechSynthesis.speak(utterance);}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function updateMetrics(){$('count').textContent=records.length;$('followup-count').textContent=records.filter(r=>r.needs).length;$('draft-count').textContent=draft&&!draft.saved?1:0;}
function renderHistory(){const el=$('history');el.replaceChildren();if(!records.length){const p=document.createElement('p');p.className='history-empty';p.textContent='还没有记录，等你来写第一条。';el.append(p);}for(const r of [...records].reverse()){const button=document.createElement('button');button.type='button';button.className='history-item';const copy=document.createElement('span');const name=document.createElement('strong');name.textContent=r.customer;const desc=document.createElement('small');desc.textContent=(r.service||'待补充项目')+' · '+r.staff;copy.append(name,desc);const time=document.createElement('time');time.textContent=r.serviceDate;button.append(copy,time);button.addEventListener('click',()=>{if(draft&&!draft.saved&&!confirm('当前有未保存的草稿，仍要查看历史记录吗？'))return;draft={...r,saved:true};showDraft();});el.append(button);}updateMetrics();}
function showDraft(){if(!draft)return;$('empty').hidden=true;$('record-form').hidden=false;for(const [id,key] of Object.entries({'customer':'customer','service':'service','staff':'staff','service-date':'serviceDate','wedding-date':'weddingDate','preferences':'preferences','needs':'needs'}))$(id).value=draft[key]||'';$('raw-text').textContent=draft.raw;$('record-state').textContent=draft.saved?'已保存在本机':'待你确认';$('record-state').classList.toggle('saved',!!draft.saved);$('record-number').textContent='WORK LOG';$('save').textContent=draft.saved?'保存修改':'确认并保存';const missing=[];if(!draft.customer)missing.push('请补充客户姓名');if(!draft.service)missing.push('服务项目待补充');if(draft.dateAssumption)missing.push(draft.dateAssumption);if(draft.dateNote)missing.push(draft.dateNote);$('missing').textContent=missing.join(' · ');updateMetrics();}
$('chat-form').addEventListener('submit',event=>{event.preventDefault();if(listening){status('请先停止语音输入，再整理记录。',true);return;}const text=$('input').value.trim();if(!text){status('先告诉我今天发生了什么吧。',true);$('input').focus();return;}if(draft&&!draft.saved&&!confirm('上一条草稿还没有保存，替换为这条新记录吗？'))return;
  const data=parser.parse(text);draft={...data,id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),staff:$('staff').value||'Miranda',saved:false};message(text,'user');showDraft();
  const reply=data.customer?`收到啦 ✨ 我把 ${data.customer} 的${data.service?' '+data.service+' ':''}记录整理好了。${data.preferences?'她的偏好是：'+data.preferences+'。':''}${data.needs?'潜在后续也标出来了。':''}请确认右侧信息，点保存后就留下来了。`:'收到啦 ✨ 这段话我保留下来了。客户姓名和没识别到的信息可以在右侧补充，确认后再保存。';message(reply);say(reply);$('input').value='';status('记录卡已生成。请检查并补充信息，尚未保存。');if(window.innerWidth<=720)$('record-form').scrollIntoView({behavior:'smooth',block:'start'});
});
$('record-form').addEventListener('submit',event=>{event.preventDefault();if(!draft)return;const customer=$('customer').value.trim();if(!customer){$('customer').focus();toast('请补充客户姓名。');return;}const next={...draft,customer,service:$('service').value,staff:$('staff').value,serviceDate:$('service-date').value,weddingDate:$('wedding-date').value,preferences:$('preferences').value.trim(),needs:$('needs').value.trim(),dateAssumption:'',dateNote:'',saved:true};const nextRecords=records.filter(r=>r.id!==next.id).concat(next);try{localStorage.setItem(storageKey,JSON.stringify(nextRecords));storageAvailable=true;}catch{status('浏览器无法保存，记录仍是草稿。请允许本地存储或换一个浏览器。',true);toast('保存失败，请保留当前页面。');return;}records=nextRecords;const wasSaved=draft.saved;draft=next;showDraft();renderHistory();const reply=`${next.customer} 的记录${wasSaved?'修改已保存':'已经保存在这台设备上啦'} ✓ 今天的用心，我帮你留下来了。`;message(reply);say(reply);toast('已保存到本机演示记录 ✓');status('本机保存成功。公司后台尚未连接。');});
document.querySelectorAll('[data-example]').forEach(button=>button.addEventListener('click',()=>{if(listening){status('请先停止语音输入。',true);return;}$('input').value=parser.examples[button.dataset.example];$('input').focus();status('已填入示例文字，点击「整理记录」开始演示。');}));
$('guide-button').addEventListener('click',()=>$('guide').showModal());$('close-guide').addEventListener('click',()=>$('guide').close());$('guide').addEventListener('click',e=>{if(e.target===$('guide')){const rect=$('guide').getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)$('guide').close();}});
$('presentation').addEventListener('click',()=>{const on=document.body.classList.toggle('presenting');$('presentation').textContent=on?'退出投屏模式':'投屏模式';$('presentation').setAttribute('aria-pressed',String(on));});
$('reset').addEventListener('click',()=>{if(!confirm('清空这台设备上的演示记录和对话，重新开始？'))return;if(listening)recognition.abort();try{localStorage.removeItem(storageKey);}catch{toast('无法清空浏览器存储，请检查设置。');return;}records=[];draft=null;$('record-form').hidden=true;$('empty').hidden=false;$('messages').replaceChildren();message('重新开始啦 ✨ 告诉我今天的第一位客户吧。');$('input').value='';renderHistory();status('演示已重置，可以重新开始。');if('speechSynthesis'in window)window.speechSynthesis.cancel();});
function idleMic(){clearTimeout(listenTimer);listening=false;$('mic').disabled=false;$('mic').classList.remove('active');$('mic-label').textContent='点击说话';$('mic').setAttribute('aria-label','开始语音输入');$('send').disabled=false;$('language').disabled=false;}
const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;
if(Recognition){$('mic').addEventListener('click',()=>{if(listening){recognition.stop();$('mic-label').textContent='正在结束…';return;}if('speechSynthesis'in window)window.speechSynthesis.cancel();const base=$('input').value.trim();let finalText='';speechError=false;recognition=new Recognition();recognition.lang=$('language').value;recognition.continuous=true;recognition.interimResults=true;recognition.maxAlternatives=1;
  recognition.onstart=()=>{$('mic').disabled=false;listening=true;$('mic').classList.add('active');$('mic-label').textContent='结束说话';$('mic').setAttribute('aria-label','结束语音输入');$('send').disabled=true;$('language').disabled=true;status('正在听。说完点「结束说话」，再检查转写文字。');listenTimer=setTimeout(()=>{recognition.stop();status('已达到 60 秒，正在结束语音转写。');},60000);};
  recognition.onresult=event=>{let interim='';for(let i=event.resultIndex;i<event.results.length;i++){const t=event.results[i][0].transcript;if(event.results[i].isFinal)finalText+=t;else interim+=t;}$('input').value=[base,finalText+interim].filter(Boolean).join(' ').slice(0,4000);};
  recognition.onerror=event=>{speechError=true;const errors={'not-allowed':'麦克风或语音服务权限未允许。请检查浏览器权限，或使用文字输入。','service-not-allowed':'浏览器未允许语音服务，请使用 Chrome 或文字输入。','audio-capture':'没有检测到可用麦克风，请检查设备设置。','network':'语音服务网络出错，可以重试或使用示例文字。','no-speech':'没有听到语音。可以再试一次，或用文字输入。','aborted':'语音输入已取消。'};status(errors[event.error]||'语音转写未完成，请重试或使用文字输入。',true);idleMic();};
  recognition.onend=()=>{idleMic();if(!speechError)status($('input').value.trim()?'转写结束，检查文字后点击「整理记录」。':'没有获取到文字，可以重试或使用示例。');};
  try{$('mic').disabled=true;$('mic-label').textContent='正在启动…';recognition.start();}catch{idleMic();status('语音服务无法启动，请重试或使用文字输入。',true);}
});}else{$('mic').disabled=true;$('mic-label').textContent='语音暂不支持';status('此浏览器不支持语音转写。请使用 Chrome，或直接输入文字。',true);}
document.addEventListener('visibilitychange',()=>{if(document.hidden&&listening)recognition.stop();});
renderHistory();if(!storageAvailable)status('无法读取本机记录，请检查浏览器存储设置。',true);
